"""
reporter.py - Generate structured HTML report of all findings
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from rich.console import Console

console = Console()
log = logging.getLogger("autopwn.reporter")


class Reporter:
    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, all_results: Dict[str, Any]):
        """Generate HTML report for all targets."""
        html = self._build_html(all_results)
        report_file = self.output_dir / "report.html"

        with open(report_file, "w") as f:
            f.write(html)

        # Also JSON
        json_file = self.output_dir / "report.json"
        with open(json_file, "w") as f:
            json.dump(all_results, f, indent=2, default=str)

        console.print(f"[green][+] HTML Report: {report_file}[/green]")
        console.print(f"[green][+] JSON Report: {json_file}[/green]")

    def _build_html(self, all_results: dict) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        targets_html = ""

        for target, results in all_results.items():
            targets_html += self._target_section(target, results)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AutoPwn Report - {timestamp}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Courier New', monospace; background: #0a0a0f; color: #c0c0c0; padding: 20px; }}
  h1 {{ color: #ff3333; text-align: center; padding: 20px; font-size: 2em; border-bottom: 2px solid #ff3333; }}
  h2 {{ color: #ff6600; margin: 20px 0 10px; border-left: 4px solid #ff6600; padding-left: 12px; }}
  h3 {{ color: #ffcc00; margin: 15px 0 8px; }}
  .target {{ background: #111118; border: 1px solid #333; border-radius: 8px; margin: 20px 0; padding: 20px; }}
  .target-header {{ background: #1a1a2e; padding: 12px; border-radius: 6px; margin-bottom: 15px; }}
  .target-ip {{ color: #00ff99; font-size: 1.4em; font-weight: bold; }}
  .os-badge {{ background: #ff6600; color: #000; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; margin-left: 10px; }}
  .section {{ margin: 15px 0; padding: 12px; background: #15151f; border-radius: 6px; border-left: 3px solid #444; }}
  .flag {{ background: #003300; border: 2px solid #00ff00; border-radius: 8px; padding: 15px; margin: 10px 0; }}
  .flag-value {{ color: #00ff00; font-size: 1.3em; font-weight: bold; font-family: monospace; }}
  .vuln {{ background: #1a0000; border-left: 3px solid #ff3333; padding: 8px 12px; margin: 5px 0; color: #ff9999; }}
  .cred {{ background: #1a1a00; border-left: 3px solid #ffff00; padding: 8px 12px; margin: 5px 0; color: #ffff99; }}
  .cmd {{ background: #0a0a0a; padding: 8px 12px; border-radius: 4px; font-family: monospace; color: #88ff88; margin: 4px 0; font-size: 0.9em; }}
  .port-table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
  .port-table th {{ background: #222; color: #ff6600; padding: 8px; text-align: left; }}
  .port-table td {{ padding: 6px 8px; border-bottom: 1px solid #333; }}
  .port-table tr:hover {{ background: #1a1a2e; }}
  .tag {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.75em; margin: 2px; }}
  .tag-red {{ background: #ff000033; color: #ff6666; border: 1px solid #ff3333; }}
  .tag-yellow {{ background: #ffff0022; color: #ffff66; border: 1px solid #ffcc00; }}
  .tag-green {{ background: #00ff0022; color: #66ff66; border: 1px solid #00cc00; }}
  .warning {{ background: #330000; border: 2px solid #ff0000; padding: 15px; border-radius: 8px;
              color: #ff9999; text-align: center; margin: 20px 0; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin: 15px 0; }}
  .metric {{ background: #1a1a2e; border: 1px solid #333; border-radius: 6px; padding: 12px; text-align: center; }}
  .metric-val {{ font-size: 2em; font-weight: bold; color: #00ff99; }}
  .metric-label {{ font-size: 0.8em; color: #888; }}
  pre {{ white-space: pre-wrap; word-break: break-all; }}
</style>
</head>
<body>
<h1>🔴 OSCP AutoPwn Report</h1>
<div class="warning">
  ⚠️ AUTHORIZED PENETRATION TESTING ONLY — GENERATED {timestamp} ⚠️
</div>
{targets_html}
<footer style="text-align:center;color:#444;margin-top:40px;padding:20px;">
  Generated by OSCP AutoPwn Framework | For Authorized Lab Use Only
</footer>
</body>
</html>"""

    def _target_section(self, target: str, results: dict) -> str:
        recon = results.get("recon", {})
        exploit = results.get("exploit", {})
        shell = results.get("shell", {})
        privesc = results.get("privesc", {})
        flags = results.get("flags", {})

        os_type = recon.get("os", "Unknown")
        ports = recon.get("ports", [])
        vulns = recon.get("vulnerabilities", [])
        creds = exploit.get("creds_found", [])
        flags_found = flags.get("flags_found", [])
        shell_vectors = exploit.get("shell_vectors", [])

        # Metrics
        metrics = f"""
<div class="summary-grid">
  <div class="metric"><div class="metric-val">{len(ports)}</div><div class="metric-label">Open Ports</div></div>
  <div class="metric"><div class="metric-val">{len(vulns)}</div><div class="metric-label">Vulnerabilities</div></div>
  <div class="metric"><div class="metric-val">{len(creds)}</div><div class="metric-label">Credentials</div></div>
  <div class="metric"><div class="metric-val">{len(flags_found)}</div><div class="metric-label">Flags Found</div></div>
  <div class="metric"><div class="metric-val">{len(shell_vectors)}</div><div class="metric-label">Shell Vectors</div></div>
</div>"""

        # Ports table
        ports_html = """<table class="port-table">
<tr><th>Port</th><th>Protocol</th><th>Service</th><th>Version</th></tr>"""
        for p in ports:
            ports_html += f"<tr><td>{p['port']}</td><td>{p['protocol']}</td><td>{p['service']}</td><td>{p.get('version','')}</td></tr>"
        ports_html += "</table>"

        # Vulnerabilities
        vulns_html = "".join(f'<div class="vuln">🔴 {v}</div>' for v in vulns[:20])

        # Credentials
        creds_html = "".join(
            f'<div class="cred">🔑 {c.get("service","")} — {c.get("username","")}:{c.get("password","")}</div>'
            for c in creds
        )

        # Flags
        flags_html = ""
        if flags_found:
            for f in flags_found:
                flags_html += f'<div class="flag"><div class="flag-value">🚩 {f["value"]}</div><div style="color:#888">Source: {f["source"]}</div></div>'
        else:
            flags_html = '<div style="color:#888">No flags auto-captured. Run hunt commands manually.</div>'

        # Shell info
        revshells = shell.get("revshell_cmds", {})
        shell_html = ""
        for stype, cmd in list(revshells.items())[:4]:
            shell_html += f'<div class="cmd"># {stype.upper()}<br>{cmd}</div>'

        # Exploit modules matched
        msf_modules = exploit.get("metasploit", [])
        msf_html = "".join(
            f'<div class="tag tag-red">{m["name"]}</div>'
            for m in msf_modules
        ) or "<span style='color:#555'>None matched</span>"

        return f"""
<div class="target">
  <div class="target-header">
    <span class="target-ip">{target}</span>
    <span class="os-badge">{os_type}</span>
  </div>

  {metrics}

  <h3>📡 Open Ports</h3>
  <div class="section">{ports_html}</div>

  <h3>⚠️ Vulnerabilities</h3>
  <div class="section">{vulns_html or '<span style="color:#555">None discovered</span>'}</div>

  <h3>🎯 Exploit Modules Matched</h3>
  <div class="section">{msf_html}</div>

  <h3>🔑 Credentials Found</h3>
  <div class="section">{creds_html or '<span style="color:#555">None found</span>'}</div>

  <h3>🐚 Reverse Shell Commands</h3>
  <div class="section">{shell_html}</div>

  <h3>🚩 Flags</h3>
  <div class="section">{flags_html}</div>
</div>
"""
